### ISSUE TITLE
Importing cyclopts fails if there is a file called "tokenize.py" in the project which imports cyclopts

### ISSUE THREAD

**Issue by RichardBowenGM** [BrianPugh/cyclopts#174]
In an empty directory:

```
rsbowen@Richards-MacBook-Pro-2 emptydir % python
Python 3.9.18 (main, Aug 29 2023, 16:34:36) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyclopts
>>> cyclopts.__version__
'2.6.2'
>>> 
rsbowen@Richards-MacBook-Pro-2 emptydir % vim tokenize.py
rsbowen@Richards-MacBook-Pro-2 emptydir % cat tokenize.py 
import cyclopts

app = cyclopts.App()
rsbowen@Richards-MacBook-Pro-2 emptydir % python
Python 3.9.18 (main, Aug 29 2023, 16:34:36) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyclopts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rsbowen/.local/lib/python3.9/site-packages/cyclopts/__init__.py", line 24, in <module>
    from cyclopts._convert import convert
  File "/Users/rsbowen/.local/lib/python3.9/site-packages/cyclopts/_convert.py", line 2, in <module>
    import inspect
  File "/Users/richard/.pyenv/versions/3.9.18/lib/python3.9/inspect.py", line 41, in <module>
    import linecache
  File "/Users/richard/.pyenv/versions/3.9.18/lib/python3.9/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/rsbowen/repos/emptydir/tokenize.py", line 3, in <module>
    app = cyclopts.App()
AttributeError: partially initialized module 'cyclopts' has no attribute 'App' (most likely due to a circular import)
rsbowen@Richards-MacBook-Pro-2 emptydir % mv tokenize.py meow.py
rsbowen@Richards-MacBook-Pro-2 emptydir % python
Python 3.9.18 (main, Aug 29 2023, 16:34:36) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyclopts
>>> cyclopts.__version__
'2.6.2'
>>> 

```

So:

* If there is a file called 'tokenize.py' in the working directory which imports and uses cyclopts, importing cyclopts will fail (this means you also can't use `tokenize.py`)
* Renaming the file fixes the problem

**Comment by BrianPugh** [comment]
Unfortunately, you cannot name the script `tokenize.py` since it collides with the python-builtin [`tokenize`](https://docs.python.org/3/library/tokenize.html) module. No action required on Cyclopts-side.
