### ISSUE TITLE
Handle parameters that don't exist

### ISSUE THREAD

**Issue by Ravencentric** [BrianPugh/cyclopts#26]
argparse:
```
> myapp --helo
Usage: myapp [-h] [--hello]
myapp: error: unrecognized arguments: --helo
```
cyclopts:
```py
 python .\test.py --hello
Traceback (most recent call last):
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\bind.py", line 314, in _convert
    cparam.validator(type_, val)
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\validators\_path.py", line 33, in __call__
    raise ValueError(f"{path} does not exist.")
ValueError: --hello does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\core.py", line 411, in parse_args
    command, bound, unused_tokens = self.parse_known_args(tokens, console=console)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\core.py", line 328, in parse_known_args
    bound, unused_tokens = create_bound_arguments(command, unused_tokens)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\bind.py", line 357, in create_bound_arguments
    coerced = _convert(mapping)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\bind.py", line 321, in _convert
    raise new_exception from e
cyclopts.exceptions.ValidationError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\raven\Documents\GitHub\test\test.py", line 30, in <module>
    app()
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\core.py", line 453, in __call__
    command, bound = self.parse_args(tokens, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\core.py", line 423, in parse_args
    console.print(format_cyclopts_error(e))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\exceptions.py", line 261, in format_cyclopts_error
    Text(str(e), "default"),
         ^^^^^^
  File "C:\Users\raven\Documents\GitHub\test\.venv\Lib\site-packages\cyclopts\exceptions.py", line 143, in __str__
    parameter_cli_name = ",".join(self.parameter2cli[self.parameter])
                                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: <Parameter "path: Annotated[pathlib.Path, Parameter(name=(), converter=None, validator=Path(exists=True, file_okay=True, dir_okay=True), negative=None, token_count=None, parse=True, show=None, show_default=None, show_choices=None, help='directory or file', show_env_var=None, env_var=())] = WindowsPath('C:/Users/raven/Documents/GitHub/test')">
```

**Comment by BrianPugh** [comment]
This should be semi-fixed in v1.1.1.  Cyclopts handles keyword arguments slightly differently than some other CLI libraries. Basically it consumes all known `--keyword value` arguments, and then parses the remaining as positional arguments. So in this case, `--helo` would be parsed as the first positional argument. Usually, this leads to subsequent errors that make it (relatively) clear what happened. Let me know how this goes after trying it on v1.1.1.

**Comment by Ravencentric** [comment]
This sort of works and sort of doesn't
```py
> python .\test.py --hello
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for PATH. --hello does not exist.                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> mkdir "--hello"

    Directory: C:\Users\raven\Documents\GitHub\test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          19-12-2023 09:56 PM                --hello

> python .\test.py --hello
path = WindowsPath('--hello')
config = WindowsPath('C:/Users/raven/Documents/GitHub/test/config.yaml')
```

The error message doesn't exactly convey what the real issue is (argument doesn't exist) and if the argument name is shared by a folder it'll be used (Although, I guess it won't be too common for people to accidentally have a folder named like an argument).

Unfortunately, I don't think I can offer a good solution either, maybe discard stuff starting with `-*` but that might be too aggressive

**Comment by Ravencentric** [comment]
sounds good to me!

**Comment by BrianPugh** [comment]
This feature has now been implemented in the `develop-v2` branch.

Docs are available at: https://cyclopts.readthedocs.io/en/develop-v2/groups.html

I will leave this issue open until v2 is released to further discuss this feature.

**Comment by Ravencentric** [comment]
Works!
```
> python .\test.py --adkadjaskdjas
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Unknown option: "--adkadjaskdjas".                                                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by BrianPugh** [comment]
closing with the release of v2. We can reopen this issue, or open a new one, should the need arise.
